;; ``resource-provider`` is implemented but not exported, so the world is unmet.
;;
;; GENERATED by `mock/scripts/gen_fixtures.ps1` -- do not hand-edit offsets or
;; lengths; re-run the generator instead.
;;
;; # Canonical ABI rules this file encodes, each established by bisection
;;
;; 1. **An interface instance must export every type its own signatures use.**
;;    With the types only at component scope, `wasmtime` rejects the component
;;    with `instance not valid to be used as export`. An earlier revision of
;;    this file blamed "a freshly aliased type identity" instead; that diagnosis
;;    was wrong and had already sent one fix in the wrong direction.
;; 2. **The return-area pointer is the core function's `i32` result, never an
;;    extra parameter.** That is the asymmetry between `canon lift` (the guest
;;    allocates the area and returns its address) and `canon lower` (the host
;;    passes it). Adding a trailing retptr parameter makes every one of these
;;    functions fail with `lowered parameter types [...] do not match parameter
;;    types [...]`.
;; 3. **A unit ok-payload does not make a `result` cheap.** `result<_, string>`
;;    still flattens past `MAX_FLAT_RESULTS` and still needs an area.
;;
;; # Per-function shapes (core signature; then what the area holds)
;;
;;   descriptor() -> descriptor-record{string,string,u32}
;;       () -> i32                            [ptr,len, ptr,len, u32]
;;   init(string) -> result<_,string>
;;       (i32,i32) -> i32                     [disc, err_ptr, err_len]
;;   health() -> result<string,string>
;;       () -> i32                            [disc, ptr, len]
;;   prepare-upgrade(string) -> result<list<u8>,string>
;;       (i32,i32) -> i32                     [disc, ptr, len]
;;   accept-upgrade(string,list<u8>) -> result<_,string>
;;       (i32,i32,i32,i32) -> i32             [disc, err_ptr, err_len]
;;   drain(u64) -> result<_,string>
;;       (i64) -> i32                         [disc, err_ptr, err_len]
;;   shutdown()
;;       () -> ()
;;   discover(option<string>) -> result<string,string>
;;       (i32,i32,i32) -> i32                 option lowers to [disc, ptr, len]
;;   inspect(string) -> result<string,string>
;;       (i32,i32) -> i32                     [disc, ptr, len]
;;   invoke(string,string,string) -> result<string,string>
;;       (i32,i32,i32,i32,i32,i32) -> i32      [disc, ptr, len]
;;
;; Behaviour is a fixed scripted answer: no clock, no imports, no randomness.
;; That is what makes it usable as a deterministic regression input.
(component
  (type $dr (record
    (field "plugin-id" string)
    (field "version" string)
    (field "state-schema-version" u32)))
  (type $list-u8 (list u8))
  (type $option-string (option string))
  (type $result-unit-string (result (error string)))
  (type $result-string-string (result string (error string)))
  (type $result-list-u8-string (result $list-u8 (error string)))
  (core module $guest
    (memory (export "memory") 1)
    (data (i32.const 16) "sandtree.mock.provider") ;; plugin_id, 22 bytes
    (data (i32.const 39) "1.0.0") ;; version, 5 bytes
    (data (i32.const 45) "{\"state\":\"healthy\"}") ;; health, 19 bytes
    (data (i32.const 65) "{\"resources\":[{\"id\":\"res-65fcdf8f7db93c9ba34110dd6e\",\"kind\":\"container\",\"provider_id\":\"plg-f79189ed4829822fdb83\",\"name\":\"mock-container\",\"state\":\"running\",\"capabilities\":[],\"metadata\":{\"image\":\"alpine:3.20\"},\"last_seen\":\"2026-10-08T00:00:00Z\"}],\"relations\":[],\"cursor\":null}") ;; discover, 274 bytes
    (data (i32.const 340) "{\"id\":\"res-65fcdf8f7db93c9ba34110dd6e\",\"kind\":\"container\",\"provider_id\":\"plg-f79189ed4829822fdb83\",\"name\":\"mock-container\",\"state\":\"running\",\"capabilities\":[],\"metadata\":{\"image\":\"alpine:3.20\"},\"last_seen\":\"2026-10-08T00:00:00Z\"}") ;; inspect, 229 bytes
    (data (i32.const 570) "{\"state\":\"succeeded\",\"result\":{\"message\":\"ok\"}}") ;; invoke, 47 bytes

    ;; Bump allocator. Mandatory: the host lowers every string parameter
    ;; through this export.
    (global $heap (mut i32) (i32.const 1024))
    (func (export "cabi_realloc")
      (param $old_ptr i32) (param $old_size i32)
      (param $align i32) (param $new_size i32)
      (result i32)
      (local $ptr i32)
      (if (i32.eqz (local.get $new_size))
        (then (return (i32.const 0))))
      (global.get $heap)
      (local.tee $ptr)
      (local.get $new_size)
      (i32.add)
      (global.set $heap)
      (local.get $ptr))

    ;; --- lifecycle ---
    (func (export "descriptor") (result i32)
      (i32.store offset=0  (i32.const 1024) (i32.const 16))
      (i32.store offset=4  (i32.const 1024) (i32.const 22))
      (i32.store offset=8  (i32.const 1024) (i32.const 39))
      (i32.store offset=12 (i32.const 1024) (i32.const 5))
      (i32.store offset=16 (i32.const 1024) (i32.const 1))
      (i32.const 1024))
    (func (export "init") (param $p i32) (param $l i32) (result i32)
      (i32.store offset=0 (i32.const 1056) (i32.const 0))
      (i32.store offset=4 (i32.const 1056) (i32.const 0))
      (i32.store offset=8 (i32.const 1056) (i32.const 0))
      (i32.const 1056))

    (func (export "health") (result i32)
      (i32.store offset=0 (i32.const 1088) (i32.const 0))
      (i32.store offset=4 (i32.const 1088) (i32.const 45))
      (i32.store offset=8 (i32.const 1088) (i32.const 19))
      (i32.const 1088))

    (func (export "prepare_upgrade") (param $p i32) (param $l i32) (result i32)
      (i32.store offset=0 (i32.const 1120) (i32.const 0))
      (i32.store offset=4 (i32.const 1120) (i32.const 0))
      (i32.store offset=8 (i32.const 1120) (i32.const 0))
      (i32.const 1120))

    (func (export "accept_upgrade")
      (param $p1 i32) (param $l1 i32) (param $p2 i32) (param $l2 i32)
      (result i32)
      (i32.store offset=0 (i32.const 1152) (i32.const 0))
      (i32.store offset=4 (i32.const 1152) (i32.const 0))
      (i32.store offset=8 (i32.const 1152) (i32.const 0))
      (i32.const 1152))

    (func (export "drain") (param $deadline i64) (result i32)
      (i32.store offset=0 (i32.const 1184) (i32.const 0))
      (i32.store offset=4 (i32.const 1184) (i32.const 0))
      (i32.store offset=8 (i32.const 1184) (i32.const 0))
      (i32.const 1184))

    (func (export "shutdown"))

    ;; --- resource-provider ---
    (func (export "discover")
      (param $disc i32) (param $p i32) (param $l i32) (result i32)
      (i32.store offset=0 (i32.const 1216) (i32.const 0))
      (i32.store offset=4 (i32.const 1216) (i32.const 65))
      (i32.store offset=8 (i32.const 1216) (i32.const 274))
      (i32.const 1216))

    (func (export "inspect") (param $p i32) (param $l i32) (result i32)
      (i32.store offset=0 (i32.const 1248) (i32.const 0))
      (i32.store offset=4 (i32.const 1248) (i32.const 340))
      (i32.store offset=8 (i32.const 1248) (i32.const 229))
      (i32.const 1248))

    (func (export "invoke")
      (param $p1 i32) (param $l1 i32) (param $p2 i32) (param $l2 i32)
      (param $p3 i32) (param $l3 i32) (result i32)
      (i32.store offset=0 (i32.const 1280) (i32.const 0))
      (i32.store offset=4 (i32.const 1280) (i32.const 570))
      (i32.store offset=8 (i32.const 1280) (i32.const 47))
      (i32.const 1280)))

  (core instance $i (instantiate $guest))

  ;; --- lifted WIT functions ---
  (func $descriptor (result $dr)
    (canon lift (core func $i "descriptor")
      (memory (core memory $i "memory")) (realloc (core func $i "cabi_realloc"))
      string-encoding=utf8))
  (func $init (param "config-json" string) (result $result-unit-string)
    (canon lift (core func $i "init")
      (memory (core memory $i "memory")) (realloc (core func $i "cabi_realloc"))
      string-encoding=utf8))
  (func $health (result $result-string-string)
    (canon lift (core func $i "health")
      (memory (core memory $i "memory")) (realloc (core func $i "cabi_realloc"))
      string-encoding=utf8))
  (func $prepare_upgrade
    (param "target-version" string) (result $result-list-u8-string)
    (canon lift (core func $i "prepare_upgrade")
      (memory (core memory $i "memory")) (realloc (core func $i "cabi_realloc"))
      string-encoding=utf8))
  (func $accept_upgrade
    (param "from-version" string) (param "state" $list-u8) (result $result-unit-string)
    (canon lift (core func $i "accept_upgrade")
      (memory (core memory $i "memory")) (realloc (core func $i "cabi_realloc"))
      string-encoding=utf8))
  (func $drain (param "deadline-ms" u64) (result $result-unit-string)
    (canon lift (core func $i "drain")
      (memory (core memory $i "memory")) (realloc (core func $i "cabi_realloc"))
      string-encoding=utf8))
  (func $shutdown (canon lift (core func $i "shutdown")))

  (func $discover
    (param "cursor" $option-string) (result $result-string-string)
    (canon lift (core func $i "discover")
      (memory (core memory $i "memory")) (realloc (core func $i "cabi_realloc"))
      string-encoding=utf8))
  (func $inspect
    (param "resource-id" string) (result $result-string-string)
    (canon lift (core func $i "inspect")
      (memory (core memory $i "memory")) (realloc (core func $i "cabi_realloc"))
      string-encoding=utf8))
  (func $invoke
    (param "resource-id" string) (param "operation" string) (param "payload-json" string)
    (result $result-string-string)
    (canon lift (core func $i "invoke")
      (memory (core memory $i "memory")) (realloc (core func $i "cabi_realloc"))
      string-encoding=utf8))

  ;; Each instance exports the types its own signatures use; without that the
  ;; encoder rejects the component outright. See rule 1 in the header.
  (instance $lifecycle
    (export "descriptor-record" (type $dr))
    (export "list-u8" (type $list-u8))
    (export "result-unit-string" (type $result-unit-string))
    (export "result-string-string" (type $result-string-string))
    (export "result-list-u8-string" (type $result-list-u8-string))
    (export "descriptor" (func $descriptor))
    (export "init" (func $init))
    (export "health" (func $health))
    (export "prepare-upgrade" (func $prepare_upgrade))
    (export "accept-upgrade" (func $accept_upgrade))
    (export "drain" (func $drain))
    (export "shutdown" (func $shutdown)))

  (instance $resource_provider
    (export "option-string" (type $option-string))
    (export "result-string-string" (type $result-string-string))
    (export "discover" (func $discover))
    (export "inspect" (func $inspect))
    (export "invoke" (func $invoke)))
  (export "sandtree:plugin/lifecycle@1.0.0" (instance $lifecycle))
)