;; A valid component that exports nothing SandTree can bind.
;;
;; GENERATED by ``mock/scripts/gen_fixtures.ps1``.
;;
;; It exists to separate "declares no package" from "declares the wrong one" --
;; both are refusals, but only one of them is a package-identity failure, and a
;; host that conflates them would report a namespace bug when the real problem is
;; that the plugin simply does not speak the ABI.
(component
  (core module $m
    (func (export "ping") (result i32) (i32.const 1)))
  (core instance $i (instantiate $m))
  (func $ping (result u32) (canon lift (core func $i "ping")))
  (export "ping" (func $ping)))